"""Initial tables fixed quotes

Revision ID: 2597c84fbcff
Revises: 
Create Date: 2026-02-04 16:30:35.493402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2597c84fbcff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True),
    sa.Column('preferred_follow_up_method', sa.String(length=60), nullable=True),
    sa.Column('best_time_to_reach', sa.String(length=20), nullable=True),
    sa.Column('retirement_timeline', sa.String(length=40), nullable=True),
    sa.Column('confidence_in_long_term_plan', sa.String(length=40), nullable=True),
    sa.Column('most_important_retirement_activity', sa.String(length=80), nullable=True),
    sa.Column('planning_to_relocate_retirement', sa.String(length=20), nullable=True),
    sa.Column('expected_retirement_income_source', sa.String(length=120), nullable=True),
    sa.Column('overall_health', sa.String(length=30), nullable=True),
    sa.Column('money_management_style', sa.String(length=120), nullable=True),
    sa.Column('investor_profile_statement', sa.String(length=200), nullable=True),
    sa.Column('investment_comfort_level', sa.String(length=40), nullable=True),
    sa.Column('main_purpose_for_investing', sa.JSON(), nullable=True),
    sa.Column('retirement_savings_range', sa.String(length=40), nullable=True),
    sa.Column('annual_household_income_range', sa.String(length=40), nullable=True),
    sa.Column('total_investable_assets_range', sa.String(length=40), nullable=True),
    sa.Column('monthly_savings_range', sa.String(length=40), nullable=True),
    sa.Column('wants_to_improve_strategy_timing', sa.String(length=60), nullable=True),
    sa.Column('current_investment_strategies', sa.JSON(), nullable=True),
    sa.Column('has_financial_advisor', sa.String(length=80), nullable=True),
    sa.Column('advisor_local_preference', sa.String(length=120), nullable=True),
    sa.Column('owns_annuity', sa.String(length=10), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_mobile_phone'), 'leads', ['mobile_phone'], unique=False)
    op.create_index(op.f('ix_leads_state_code'), 'leads', ['state_code'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('state_limit', sa.Integer(), nullable=True),
    sa.Column('daily_download_limit', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('advisor', 'admin', name='user_role_enum'), server_default='advisor', nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('lead_downloads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('csv_batch_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_downloads_csv_batch_id'), 'lead_downloads', ['csv_batch_id'], unique=False)
    op.create_index(op.f('ix_lead_downloads_downloaded_at'), 'lead_downloads', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_lead_downloads_lead_id'), 'lead_downloads', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_downloads_user_id'), 'lead_downloads', ['user_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('license_number', sa.String(length=80), nullable=False),
    sa.Column('license_type', sa.String(length=80), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='license_verification_status_enum'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'license_number', name='uq_licenses_state_number')
    )
    op.create_index(op.f('ix_licenses_user_id'), 'licenses', ['user_id'], unique=False)
    op.create_index(op.f('ix_licenses_verified_by'), 'licenses', ['verified_by'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', 'unpaid', 'incomplete', 'incomplete_expired', 'paused', name='subscription_status_enum'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_licenses_verified_by'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_user_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_lead_downloads_user_id'), table_name='lead_downloads')
    op.drop_index(op.f('ix_lead_downloads_lead_id'), table_name='lead_downloads')
    op.drop_index(op.f('ix_lead_downloads_downloaded_at'), table_name='lead_downloads')
    op.drop_index(op.f('ix_lead_downloads_csv_batch_id'), table_name='lead_downloads')
    op.drop_table('lead_downloads')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_leads_state_code'), table_name='leads')
    op.drop_index(op.f('ix_leads_mobile_phone'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
