"""Add stripe_price_id

Revision ID: 7b4ab24c1706
Revises: 2597c84fbcff
Create Date: 2026-02-05 10:54:50.443445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4ab24c1706'
down_revision: Union[str, None] = '2597c84fbcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('stripe_price_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'subscription_plans', ['stripe_price_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_plans', type_='unique')
    op.drop_column('subscription_plans', 'stripe_price_id')
    # ### end Alembic commands ###
