"""LeadOutcome

Revision ID: ff8847dbae31
Revises: 7b4ab24c1706
Create Date: 2026-02-06 14:22:55.538596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8847dbae31'
down_revision: Union[str, None] = '7b4ab24c1706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'appointment_set', name='lead_outcome_status_enum'), server_default=sa.text("'new'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lead_id', name='uq_lead_outcomes_user_lead')
    )
    op.create_index(op.f('ix_lead_outcomes_lead_id'), 'lead_outcomes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_outcomes_status'), 'lead_outcomes', ['status'], unique=False)
    op.create_index(op.f('ix_lead_outcomes_user_id'), 'lead_outcomes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_outcomes_user_id'), table_name='lead_outcomes')
    op.drop_index(op.f('ix_lead_outcomes_status'), table_name='lead_outcomes')
    op.drop_index(op.f('ix_lead_outcomes_lead_id'), table_name='lead_outcomes')
    op.drop_table('lead_outcomes')
    # ### end Alembic commands ###
